const {chromium}=require('playwright');const fs=require('fs');const path=require('path');
const dir=__dirname,assets=path.resolve(dir,'../../experience/assets');
const font=n=>fs.readFileSync(path.join(assets,n)).toString('base64');
const D=font('playfair-display-sc.ttf'),B=font('libre-baskerville-regular.ttf');
const msg=(who,text,right=false)=>`<section class="msg ${right?'right':''}"><label>${who}</label><p>${text}</p></section>`;
const slides=[
 {tag:'NEGOCIACIÓN ENTRE AGENTES',title:'Tu agente de IA.<br>El del proveedor.<br>Una negociación.',body:`<p class="lead">Así podrían acordar una compra<br>con las reglas de tu negocio.</p><div class="network"><span>COMPRADOR</span><b>⇄</b><span>PROVEEDOR</span></div><p class="fine">Ejemplo hipotético, paso a paso →</p>`,cover:true},
 {tag:'01 · LAS REGLAS',title:'Antes de negociar,<br>definís los límites.',body:`<div class="rules"><div><b>100</b><span>unidades del mismo artículo</span></div><div><b>$130.000</b><span>tope final · impuestos y envío incluidos</span></div><div><b>48 h</b><span>plazo máximo de entrega</span></div></div><p class="fine">ARS · Pago contra entrega.<br>El tope es interno: no tenés que revelarlo.</p>`},
 {tag:'02 · LA PRIMERA OFERTA',title:'Uno consulta.<br>El otro cotiza.',body:msg('AGENTE COMPRADOR','Necesito 100 unidades en 48 h. ¿Total con impuestos y envío?')+msg('AGENTE PROVEEDOR','$138.000 finales. Entrega en 72 h. Pago contra entrega.',true)+`<p class="fine">Esta oferta no cumple precio ni plazo.</p>`},
 {tag:'03 · LA CONTRAPROPUESTA',title:'Negociar es ajustar<br>las condiciones.',body:msg('AGENTE COMPRADOR','¿$128.000 finales y entrega en 48 h? Misma cantidad y pago contra entrega.')+msg('AGENTE PROVEEDOR','Puedo ofrecer $129.000 finales en 48 h. Mismo pago. Oferta válida hoy.',true)},
 {tag:'04 · EL CONTROL',title:'La oferta cumple.<br>Vos decidís.',body:`<div class="result"><label>PROPUESTA PARA REVISAR</label><b>$129.000</b><p>100 unidades · entrega en 48 h<br>Impuestos y envío incluidos<br>Pago contra entrega</p></div><p class="lead">En este ejemplo, la orden se emite<br>solo después de tu aprobación.</p><p class="fine">Si cambian las condiciones, se vuelve a revisar.</p>`},
 {tag:'LA DECISIÓN DE TU NEGOCIO',title:'¿Qué le dejarías<br>negociar a tu IA?',body:`<div class="choices"><span>Precio</span><span>Entrega</span><span>Forma de pago</span></div><p class="lead">¿Y qué condición<br>aprobarías siempre vos?</p><p class="fine">Contá tu rubro y dónde pondrías el límite.</p>`}
];
function html(s,i){return `<!doctype html><meta charset="utf-8"><style>
@font-face{font-family:P;src:url(data:font/ttf;base64,${D})}@font-face{font-family:B;src:url(data:font/ttf;base64,${B})}*{box-sizing:border-box}body{margin:0;width:1080px;height:1350px;background:#11141b;color:#eef0f4;font-family:B}main{position:relative;width:1080px;height:1350px;padding:65px 76px;overflow:hidden}header{display:flex;justify-content:space-between;border-bottom:1px solid #94a4bc66;padding-bottom:31px;color:#aab7cb;font:20px monospace;letter-spacing:2px}.brand{color:#eef0f4;font:30px P;letter-spacing:0}.tag{margin:46px 0 37px;color:#94a4bc;font:22px monospace;letter-spacing:2px}h1{font:normal 77px/1.15 P;margin:0 0 40px;letter-spacing:-3px}.cover h1{font-size:89px;margin-top:76px}.lead{font:32px/1.6 B;color:#c8d0dc;margin:36px 0}.fine{font:24px/1.6 B;color:#a3afc2;margin:30px 0}.network{margin:65px 0 40px;display:flex;align-items:center;justify-content:space-between;border-top:1px solid #526075;border-bottom:1px solid #526075;padding:30px 5px;font:22px monospace;color:#aab7cb}.network b{font:80px B;color:#eef0f4}.msg{border:1px solid #536075;padding:31px 34px;margin:28px 70px 0 0;background:#151b25}.msg.right{margin:25px 0 0 70px;background:#1c2533;border-color:#8190a8}.msg label,.result label{color:#aab7cb;font:20px monospace;letter-spacing:2px}.msg p{font:32px/1.45 B;margin:20px 0 0}.rules{margin-top:30px}.rules div{padding:23px 0;border-bottom:1px solid #536075;display:flex;flex-direction:column;gap:12px}.rules b{font:62px P;font-weight:normal}.rules span{font:26px/1.5 B;color:#b9c3d4}.result{border:1px solid #8190a8;background:#19212d;padding:38px}.result b{display:block;font:92px/1.5 P;font-weight:normal}.result p{font:27px/1.8 B;margin:0;color:#c8d0dc}.choices{display:flex;flex-wrap:wrap;gap:18px;margin:60px 0}.choices span{border:1px solid #7d8ca4;padding:25px 28px;font:32px B}.footer{position:absolute;bottom:62px;left:76px;right:76px;border-top:1px solid #94a4bc66;padding-top:26px;display:flex;justify-content:space-between;color:#94a4bc;font:18px monospace;letter-spacing:1px}.art{position:absolute;right:-230px;bottom:160px;width:550px;height:550px;border:1px solid #94a4bc13;border-radius:50%;pointer-events:none;z-index:-1}
</style><main class="${s.cover?'cover':''}"><header><span class="brand">IMÁN</span><span>IDEAS PARA TU NEGOCIO</span></header><div class="tag">${s.tag}</div><h1>${s.title}</h1>${s.body}<div class="footer"><span>${i>0&&i<5?'EJEMPLO HIPOTÉTICO · NO ES UN CASO REAL':'ESTUDIO.IMAN'}</span><span>0${i+1} / 06</span></div></main>`}
(async()=>{const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1080,height:1350},deviceScaleFactor:1});for(let i=0;i<slides.length;i++){const markup=html(slides[i],i);fs.writeFileSync(path.join(dir,`0${i+1}.html`),markup);await page.setContent(markup);await page.evaluate(()=>document.fonts.ready);const overflow=await page.locator('.footer').evaluate(el=>{const p=el.previousElementSibling;return p.getBoundingClientRect().bottom>el.getBoundingClientRect().top-12});if(overflow)throw Error(`Slide ${i+1} overlaps footer`);await page.screenshot({path:path.join(dir,`0${i+1}.png`)});}await browser.close();console.log('6 slides rendered; footer clearance verified.');})().catch(e=>{console.error(e);process.exit(1)});
