"""Purpose-built industry landing pages. Import build_industry_pages() from build.py."""
from html import escape

E = escape
CAL = 'https://agenda.iman.ar'
COFFEE_IMAGE = 'https://cafe.iman.ar/cafe/campaign/ritual-v2.webp'


def cta(label, href='#contacto', secondary=False):
    extra = ' target="_blank" rel="noopener"' if href.startswith('https://') else ''
    return f'<a class="button {"secondary" if secondary else ""}" href="{E(href, quote=True)}"{extra}>{label}<span aria-hidden="true">↗</span></a>'


def icon(kind):
    drawings = {
        'pet': '<path d="m39 22 9 6h36l9-6 9 109H30Z" fill="#eceaff" stroke="#5e57c9" stroke-width="2"/><path d="M35 49h62v51H35z" fill="#625adb"/><path d="M56 73c-5 0-9 7-5 11 4 3 6 0 10 0s7 3 10 0c4-4 0-11-5-11Z" fill="white"/><circle cx="51" cy="65" r="4" fill="white"/><circle cx="61" cy="61" r="4" fill="white"/><circle cx="72" cy="65" r="4" fill="white"/><path d="M43 115h45" stroke="#aaa4df" stroke-width="4"/>',
        'ropa': '<path d="m43 30 16-7c1 12 23 12 24 0l16 7 22 23-16 17-10-8v68H47V62l-10 8-16-17Z" fill="#c8c5f0" stroke="#9892c9" stroke-width="2"/><path d="M59 23c2 14 23 14 24 0M47 60l4-18M95 60l-4-18" fill="none" stroke="#9892c9" stroke-width="2"/><path d="M56 114h30" stroke="#aaa4da" stroke-width="2"/>',
        'limpieza': '<rect x="46" y="29" width="38" height="18" rx="3" fill="#4f46f5"/><path d="M47 47h36l10 18v64H37V66Z" fill="#d9eae5" stroke="#83afa0" stroke-width="2"/><rect x="41" y="80" width="48" height="31" rx="2" fill="#fff"/><path d="m64 84 7 13-7 8-7-8Z" fill="#4f46f5"/><path d="M44 64h43" stroke="#adcec1" stroke-width="2"/>',
        'repuestos': '<path d="m49 42 31-8 15 16 5 69-55 7-9-70Z" fill="#373b47"/><path d="m48 42-1-16 30-4 3 12" fill="#666a78"/><path d="m47 59 36-5 5 39-39 5Z" fill="#736cee"/><path d="m69 62 8 16-7 10-9-10Z" fill="#fff"/><path d="m51 110 33-4" stroke="#8e91a0" stroke-width="4"/>',
        'box': '<path d="m21 48 47-24 48 23v66l-48 23-47-24Z" fill="#e1d0b8" stroke="#ac9174" stroke-width="2"/><path d="m21 48 47 23 48-24M68 71v65M44 36l47 23v24l-15 7V66" fill="none" stroke="#ac9174" stroke-width="2"/><path d="m35 86 20 10m-20-2 13 6" stroke="#fff" stroke-width="3"/>',
    }
    return f'<svg class="industry-product-art" viewBox="0 0 140 154" fill="none" aria-hidden="true">{drawings.get(kind, drawings["box"])}</svg>'


def demo_note(label):
    return f'<figcaption class="industry-demo-note">{label} · Ejemplo ilustrativo, personalizable para tu negocio.</figcaption>'


def cafe_scene():
    return f'''<figure class="industry-scene industry-scene-cafe" aria-label="Ejemplo de programa de cafetería: tarjeta de beneficios en Wallet y mensaje de una campaña de café.">
      <div class="industry-halo" aria-hidden="true"></div>
      <div class="industry-cafe-photo"><img src="{COFFEE_IMAGE}" alt="Café servido con una propuesta para disfrutar en la cafetería" fetchpriority="high"><div><span>EL RITUAL DE SIEMPRE</span><strong>Un café.<br>Una buena razón<br>para volver.</strong></div></div>
      <div class="industry-wallet-phone"><div class="industry-device-top"><span>9:41</span><i></i><span>●●</span></div><p class="industry-phone-label">Tu tarjeta del Club</p><div class="industry-wallet-pass"><div><b>CAFÉ</b><span>CLUB DE HABITUALES</span></div><p>El próximo<br>tiene premio.</p><div class="industry-stamps" aria-label="Cuatro visitas de seis en este ejemplo"><i>✓</i><i>✓</i><i>✓</i><i>✓</i><i></i><i></i></div><small>Un beneficio elegido por tu café.</small><div class="industry-code" aria-hidden="true"></div></div><span class="industry-wallet-label">Apple Wallet · Google Wallet</span></div>
      <div class="industry-floating-message"><span class="industry-message-symbol" aria-hidden="true">↗</span><div><small>CLUB CAFÉ · BENEFICIO DISPONIBLE</small><b>Tu pausa de hoy tiene un extra.</b><p>Consultá el beneficio en tu tarjeta.</p></div></div>
      {demo_note('Vista de Wallet y campaña')}
    </figure>'''


def retail_scene(d):
    return f'''<figure class="industry-scene industry-scene-retail" aria-label="Ejemplo de catálogo y mensaje de {E(d['name'].lower())}"><div class="industry-halo" aria-hidden="true"></div>
      <div class="industry-shop-window"><div class="industry-browser-bar"><i></i><i></i><i></i><span>Tu comercio · Catálogo</span></div><div class="industry-shop-head"><b>{d['brand']}</b><span>Catálogo / Mi Club</span></div><div class="industry-retail-product"><div>{icon(d['art'])}</div><span>{d['product_category']}</span><h3>{d['product']}</h3><p>{d['product_detail']}</p><span class="industry-demo-pill">{d['product_action']}</span></div><div class="industry-shop-bottom"><span>Tu marca</span><span>Tu relación con cada cliente</span></div></div>
      <div class="industry-mini-wallet"><span>MI TARJETA DEL CLUB</span><strong>{d['wallet_title']}</strong><div><b>{d['brand']}</b><span aria-hidden="true">◈</span></div></div>
      <div class="industry-floating-message"><span class="industry-message-symbol" aria-hidden="true">↗</span><div><small>{d['notification_label']}</small><b>{d['notification']}</b><p>{d['notification_detail']}</p></div></div>{demo_note('Catálogo, Wallet y mensaje')}
    </figure>'''


def wholesale_scene(d):
    rows = ''.join(f'<div class="industry-order-row"><span>{icon(d["art"])}</span><div><b>{name}</b><small>{unit}</small></div><span class="industry-qty">{qty}</span></div>' for name, unit, qty in d['order_rows'])
    return f'''<figure class="industry-scene industry-scene-wholesale" aria-label="Ejemplo de pedido mayorista con productos, presentaciones y revisión comercial"><div class="industry-halo" aria-hidden="true"></div><div class="industry-order-board"><div class="industry-browser-bar"><i></i><i></i><i></i><span>Tu distribuidora · Pedidos</span></div><div class="industry-order-heading"><span>CATÁLOGO MAYORISTA</span><h3>La próxima reposición,<br>en un solo pedido.</h3><p>{d['board_customer']}</p></div><div class="industry-order-columns"><span>Producto y presentación</span><span>Cantidad</span></div>{rows}<div class="industry-order-foot"><span>Condiciones del comercio</span><b>Listo para revisar ↗</b></div></div><div class="industry-b2b-note"><span class="industry-b2b-check" aria-hidden="true">✓</span><div><small>{d['board_note_label']}</small><strong>{d['board_note']}</strong><p>{d['board_note_detail']}</p></div></div>{demo_note('Pedido mayorista')}
    </figure>'''


def transport_scene():
    return f'''<figure class="industry-scene industry-scene-transport" aria-label="Ejemplo de seguimiento de reparto por etapas confirmadas"><div class="industry-halo" aria-hidden="true"></div><div class="industry-route-board"><div class="industry-browser-bar"><i></i><i></i><i></i><span>Tu operación · Seguimiento</span></div><div class="industry-route-heading"><small>PEDIDO DE EJEMPLO · R-028</small><h3>Cada etapa,<br>bien comunicada.</h3><span>En reparto</span></div><svg class="industry-route-map" viewBox="0 0 420 180" aria-hidden="true"><path d="M0 40h420M0 100h420M0 160h420M60 0v180M150 0v180M240 0v180M330 0v180" stroke="#ddddeb" stroke-width="15"/><path d="M60 132V40h180v60h90" stroke="#4F46F5" stroke-width="5" fill="none" stroke-linecap="round" stroke-dasharray="8 7"/><circle cx="60" cy="132" r="10" fill="#4F46F5" stroke="white" stroke-width="4"/><circle cx="330" cy="100" r="10" fill="#4F46F5" stroke="white" stroke-width="4"/></svg><ol class="industry-route-steps"><li class="done"><i>✓</i><span>Preparado<small>Confirmado por depósito</small></span></li><li class="done"><i>✓</i><span>En reparto<small>El cliente recibe el aviso</small></span></li><li><i>3</i><span>Entregado<small>Pendiente de confirmación</small></span></li></ol></div><div class="industry-floating-message"><span class="industry-message-symbol" aria-hidden="true">↗</span><div><small>ACTUALIZACIÓN DEL PEDIDO</small><b>Tu pedido ya está en reparto.</b><p>Seguí sus etapas desde este enlace.</p></div></div>{demo_note('Etapas de entrega; mapa esquemático, sin GPS en vivo')}
    </figure>'''


def campaign_preview(d):
    if d['kind'] == 'wholesale':
        return f'''<div class="industry-campaign-preview industry-proposal"><div class="industry-mail-chrome"><span>REPOSICIÓN MAYORISTA</span><span aria-hidden="true">↗</span></div><div class="industry-mail-body"><span class="industry-mail-label">{d['campaign_to']}</span><h3>{d['campaign_message_title']}</h3><p>{d['campaign_message']}</p><div class="industry-proposal-items">{''.join(f'<span><i aria-hidden="true">✓</i>{item}</span>' for item in d['proposal_items'])}</div><span class="industry-email-cta">Revisar propuesta de pedido →</span></div><p class="industry-preview-disclaimer">Ejemplo de propuesta. Precio, stock y aprobación se verifican antes de confirmar.</p></div>'''
    if d['kind'] == 'transport':
        return '''<div class="industry-campaign-preview"><div class="industry-mail-chrome"><span>EXCEPCIÓN DE ENTREGA</span><span aria-hidden="true">↗</span></div><div class="industry-mail-body"><span class="industry-mail-label">PARA EL EQUIPO DE OPERACIONES</span><h3>Falta confirmar<br>la dirección.</h3><p>El pedido queda identificado, con el motivo y el responsable del próximo paso.</p><div class="industry-issue-detail"><span>Estado <b>Requiere revisión</b></span><span>Motivo <b>Datos incompletos</b></span><span>Acción <b>Contactar al destinatario</b></span></div><span class="industry-email-cta">Abrir el caso →</span></div><p class="industry-preview-disclaimer">Ejemplo ilustrativo de derivación. Los canales se acuerdan con tu operación.</p></div>'''
    photo = f'<img class="industry-email-photo" src="{COFFEE_IMAGE}" alt="Propuesta de café para una campaña de fidelización" loading="lazy">' if d['kind'] == 'cafe' else f'<div class="industry-email-product">{icon(d["art"])}</div>'
    return f'''<div class="industry-campaign-preview"><div class="industry-mail-chrome"><span>EMAIL · CAMPAÑA DEL CLUB</span><span aria-hidden="true">↗</span></div><div class="industry-mail-body"><span class="industry-mail-label">{d['campaign_to']}</span><h3>{d['campaign_message_title']}</h3><p>{d['campaign_message']}</p>{photo}<span class="industry-email-cta">{d['campaign_action']} →</span><small>Recibís este mensaje porque elegiste ser parte del Club.<br>Podés dejar de recibir estas comunicaciones.</small></div><p class="industry-preview-disclaimer">Ejemplo de contenido. Beneficios y condiciones definidos por tu negocio.</p></div>'''


def body(d):
    scene = cafe_scene() if d['kind'] == 'cafe' else wholesale_scene(d) if d['kind'] == 'wholesale' else transport_scene() if d['kind'] == 'transport' else retail_scene(d)
    hooks = ''.join(f'<li><span aria-hidden="true">✓</span>{text}</li>' for text in d['hooks'])
    channels = ''.join(f'<span>{text}</span>' for text in d['channels'])
    uses = ''.join(f'<article><span class="industry-use-number">0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>' for i, (title, desc) in enumerate(d['uses']))
    steps = ''.join(f'<article><span>0{i+1}</span><div><h3>{title}</h3><p>{desc}</p></div></article>' for i, (title, desc) in enumerate(d['steps']))
    related = ''.join(f'<a href="{path}"><span>{label}<small>{description}</small></span><span aria-hidden="true">↗</span></a>' for label,description,path in d['related'])
    return f'''<div class="vertical-page vertical-{d['slug']}"><section class="industry-hero"><div class="wrap"><nav class="breadcrumbs" aria-label="Ruta de navegación"><a href="/">IMAN</a><span aria-hidden="true">/</span><span>{d['name']}</span></nav><div class="industry-hero-grid"><div class="industry-hero-copy"><p class="eyebrow">{d['eyebrow']}</p><h1>{d['headline']}</h1><p class="lead">{d['intro']}</p><div class="actions">{cta(d['cta'])}{cta('Agendar 30 minutos',CAL,True)}</div><p class="industry-hero-micro">Demo personalizada. Propuesta con alcance y presupuesto, sin compromiso.</p><ul class="industry-checks">{hooks}</ul></div>{scene}</div><div class="industry-channel-strip"><strong>{d['strip_title']}</strong><div>{channels}</div></div></div></section>
    <section class="industry-use-section"><div class="wrap"><div class="industry-section-heading"><p class="eyebrow">{d['uses_eyebrow']}</p><h2>{d['uses_title']}</h2></div><div class="industry-uses">{uses}</div></div></section>
    <section class="industry-campaign-section" id="campana"><div class="wrap industry-campaign-grid"><div class="industry-campaign-copy"><p class="eyebrow">{d['campaign_eyebrow']}</p><h2>{d['campaign_title']}</h2><p class="lead">{d['campaign_intro']}</p><ul class="industry-campaign-points">{''.join(f'<li><span aria-hidden="true">✓</span><div><b>{title}</b><p>{desc}</p></div></li>' for title,desc in d['campaign_points'])}</ul>{cta(d['campaign_cta'])}<p class="industry-platform-note">{d['platform_note']}</p></div>{campaign_preview(d)}</div></section>
    <section class="industry-journey"><div class="wrap"><div class="industry-section-heading"><p class="eyebrow">{d['journey_eyebrow']}</p><h2>{d['journey_title']}</h2></div><div class="industry-journey-grid">{steps}</div></div></section>
    <section class="industry-related"><div class="wrap"><div><p class="eyebrow">{d['related_eyebrow']}</p><h2>{d['related_title']}</h2></div><div class="industry-related-links">{related}</div></div></section></div>'''


WALLET_NOTE = 'Wallet se desarrolla con la identidad de tu negocio. Los avisos dependen de los permisos del cliente y de las reglas de Apple y Google; email completa la comunicación.'

RETAIL_COMMON = {
    'kind':'retail', 'service':'Fidelización con Wallet y catálogo digital', 'contact_service':'IMAN Fidelización',
    'strip_title':'Tu marca, después de cada compra.', 'channels':['Apple Wallet','Google Wallet','Notificaciones','Email','Catálogo'],
    'campaign_eyebrow':'Una campaña que tu cliente entiende', 'platform_note':WALLET_NOTE,
    'journey_eyebrow':'Así lo usa tu cliente', 'related_eyebrow':'La relación y la compra, conectadas',
    'related_title':'Que vuelva.<br>Y que comprar sea fácil.',
    'related':[('IMAN Fidelización','Wallet, beneficios y campañas con tu marca.','/fidelizacion/'),('IMAN Comercios','Catálogo digital y pedidos bien armados.','/comercios/')],
}


def build_industry_pages():
    """Return {canonical_path: page kwargs}; includes no global footer/contact markup."""
    data = [
      {
        **RETAIL_COMMON,'slug':'gastronomia','kind':'cafe','path':'/gastronomia/','name':'Cafeterías y gastronomía','eyebrow':'IMAN para cafeterías y gastronomía',
        'title':'Fidelización para cafeterías y restaurantes con Wallet | IMAN',
        'description':'Convertí visitas en clientes habituales con un Club de tu cafetería: Apple Wallet, Google Wallet, beneficios, notificaciones, email y carta digital.',
        'headline':'El próximo café,<br><em>que sea con vos.</em>',
        'intro':'Tu café ya les gustó. Dales una razón para volver: un Club con tu marca, beneficios en Wallet y mensajes que invitan a la próxima visita.',
        'cta':'Quiero el Club de mi café','hooks':['Sin pedir otra app','Beneficios que definís vos','También para bares y restaurantes'],
        'uses_eyebrow':'Del ticket a la próxima visita','uses_title':'Un café se termina.<br><em>La relación, no.</em>',
        'uses':[('Una visita que queda','Un QR en el mostrador o la mesa invita a sumarse al Club. La tarjeta se guarda en el teléfono del cliente.'),('Un motivo para elegirte','Visitas, puntos o beneficios seleccionados por vos. Un premio que tenga sentido para el cliente y para el margen de tu café.'),('Un mensaje con algo para ofrecer','Un beneficio disponible, una novedad de la carta o una propuesta para la merienda. Wallet y email, con el permiso del cliente.')],
        'campaign_to':'DE TU CAFÉ, PARA SUS HABITUALES','campaign_title':'Esa merienda que<br>merece <em>otra visita.</em>',
        'campaign_intro':'Pensá en quien vino por primera vez y todavía no volvió. El Club te permite mantener el contacto y acercarle una propuesta concreta.',
        'campaign_message_title':'Tu próxima pausa<br>te está esperando.', 'campaign_message':'Tenemos una propuesta del Club para tu próxima merienda. Mirá el beneficio y elegí cuándo volver.', 'campaign_action':'Ver mi beneficio',
        'campaign_points':[('La ocasión','Desayuno, merienda o una franja que quieras trabajar: elegís qué visita incentivar.'),('El beneficio','Un extra, un producto seleccionado o un premio por frecuencia, con condiciones claras.'),('La vuelta al local','El cliente consulta el beneficio y lo valida según el circuito acordado con tu equipo.')],
        'campaign_cta':'Armarlo para mi cafetería', 'journey_title':'Del mostrador<br><em>a su Wallet.</em>',
        'steps':[('Escanea y se suma','El QR lo lleva al alta de tu Club, con una explicación clara del beneficio y el permiso de contacto.'),('Guarda su tarjeta','Apple Wallet o Google Wallet: encuentra su identidad de socio y sus beneficios sin descargar otra app.'),('Vuelve y usa el beneficio','Tu equipo valida el canje con las reglas del Club. Esa visita queda vinculada al programa.')],
        'faqs':[('¿Sirve para restaurantes y bares, además de cafeterías?','Sí. El programa puede organizarse alrededor de visitas, consumos o beneficios. Cambian la propuesta, la validación y las campañas: una merienda no se comunica igual que una cena o un almuerzo.'),('¿Mis clientes tienen que descargar una app?','La tarjeta se guarda en Apple Wallet o Google Wallet desde un enlace o QR. La compatibilidad y el recorrido de alta se prueban como parte de la implementación.'),('¿Se puede sumar la carta y recibir pedidos?','Sí. IMAN Comercios puede sumar una carta digital y un recorrido para armar pedidos. El alcance distingue catálogo, recepción del pedido, pagos e integración con el sistema del local.')],
      },
      {
        **RETAIL_COMMON,'slug':'pet','path':'/pet/','name':'Pet shops y forrajerías','eyebrow':'IMAN para pet shops y forrajerías',
        'title':'Fidelización y recompra para pet shops con Wallet | IMAN','description':'Club de clientes, Wallet, recordatorios de reposición y catálogo digital para pet shops y forrajerías. Una próxima compra conectada con tu negocio.',
        'headline':'La próxima bolsa,<br><em>que la compren<br>con vos.</em>','intro':'La comida se repone. La relación también se cuida. Conectá el historial de compra con beneficios, recordatorios y un catálogo listo para volver a pedir.',
        'cta':'Quiero verlo en mi pet shop','hooks':['Alimento, accesorios y recurrencia','Wallet con tu marca','Pedidos con producto y presentación'],
        'brand':'TU PET SHOP','art':'pet','product_category':'ALIMENTO · ADULTOS','product':'El alimento de siempre','product_detail':'Presentaciones y variantes bien identificadas.','product_action':'Volver a pedir →','wallet_title':'Su próxima compra,<br>con beneficios.', 'notification_label':'TU PET SHOP · CLUB','notification':'¿Es momento de reponer?','notification_detail':'Encontrá su alimento y el beneficio del Club.',
        'uses_eyebrow':'Más que vender una bolsa','uses_title':'Su alimento cambia.<br><em>Su pet shop, que no.</em>',
        'uses':[('La reposición con contexto','Usá el producto, la presentación y el historial para proponer un seguimiento. La fecha se estima con tus datos y se ajusta con el cliente.'),('Un Club para compras habituales','Premiá la recurrencia con beneficios que el cliente encuentra en Wallet. Vos definís productos, vigencia y condiciones.'),('El pedido, sin confusiones','Un catálogo con marca, variedad y tamaño de bolsa. El cliente vuelve a elegir lo que necesita y tu equipo recibe un pedido claro.')],
        'campaign_to':'DE TU PET SHOP, PARA SUS CLIENTES','campaign_title':'Aparecé cuando<br>toca <em>reponer.</em>','campaign_intro':'Un recordatorio útil empieza por lo que ya compró. La campaña conecta el alimento habitual, una forma fácil de pedirlo y un beneficio del Club.',
        'campaign_message_title':'Su alimento de siempre.<br>Tu pet shop de confianza.','campaign_message':'¿Estás por reponer? Consultá las presentaciones y el beneficio disponible en tu Club.','campaign_action':'Ver alimento y beneficios',
        'campaign_points':[('El producto correcto','Marca, variedad y presentación del historial, sin sustituir productos automáticamente.'),('Un ritmo aproximado','El recordatorio se basa en fechas y compras registradas; no presume cuánto consume cada mascota.'),('Un pedido claro','El enlace abre el catálogo para elegir y confirmar lo que hace falta.')],
        'campaign_cta':'Preparar mi campaña de reposición','journey_title':'De la primera bolsa<br><em>a las próximas.</em>',
        'steps':[('Se suma al Club','Tu cliente guarda su tarjeta y elige recibir comunicaciones de tu pet shop.'),('Compra y suma','El programa registra la compra con el circuito acordado y aplica sus reglas de beneficios.'),('Repone desde el catálogo','El recordatorio lleva al producto y a su presentación. Tu equipo confirma disponibilidad y pedido.')],
        'faqs':[('¿El sistema sabe cuándo se termina el alimento?','Puede estimar una oportunidad de reposición usando el historial de compra. No conoce el consumo real de cada mascota: la frecuencia se ajusta con los datos disponibles y las preferencias del cliente.'),('¿Funciona si hoy registro mis ventas en una planilla?','Revisamos la estructura de esa planilla y cómo identificar clientes, productos y fechas. La propuesta define cómo se importan o actualizan los datos y qué tareas conserva tu equipo.'),('¿Soy distribuidora pet: es la misma solución?','La venta mayorista requiere presentaciones, condiciones por comercio y seguimiento de cartera. <a href="/petshops/distribuidora/">Conocé la propuesta para distribuidoras pet</a>.')],
      },
      {
        **RETAIL_COMMON,'slug':'ropa','path':'/ropa/','name':'Indumentaria','eyebrow':'IMAN para tiendas de indumentaria',
        'title':'Fidelización y catálogo para tiendas de ropa | IMAN','description':'Conectá tu próxima colección con quienes ya te compraron: Club en Wallet, campañas de email y catálogo digital para tiendas de indumentaria.',
        'headline':'Tu nueva colección.<br><em>Sus ganas<br>de volver.</em>','intro':'No dejes la relación en una bolsa con tu logo. Invitá a tus clientes a un Club con beneficios, novedades relevantes y tu catálogo siempre a mano.',
        'cta':'Quiero el Club de mi tienda','hooks':['Novedades para cada segmento','Beneficios con tu identidad','Catálogo con talles y variantes'],
        'brand':'TU TIENDA','art':'ropa','product_category':'NUEVA COLECCIÓN','product':'Una nueva favorita','product_detail':'Colores, talles y detalles en un mismo lugar.','product_action':'Ver la colección →','wallet_title':'Un Club que va<br>con tu estilo.','notification_label':'TU TIENDA · NOVEDADES','notification':'La nueva colección ya llegó.','notification_detail':'Conocela y consultá tu beneficio del Club.',
        'uses_eyebrow':'La venta no termina en la caja','uses_title':'Que recuerden el look.<br><em>Y dónde lo encontraron.</em>',
        'uses':[('Un vínculo después de la compra','Un QR o enlace suma al cliente a tu Club. Su tarjeta queda en Wallet, con los beneficios y la identidad de tu tienda.'),('Novedades que tienen sentido','Campañas por compras y preferencias registradas: nuevas colecciones, categorías o acceso anticipado, con autorización del cliente.'),('Una vidriera lista para compartir','El catálogo muestra prendas, talles y colores. La consulta llega con el producto identificado y menos idas y vueltas.')],
        'campaign_to':'DE TU TIENDA, PARA SU CLUB','campaign_title':'Una colección nueva.<br><em>Una invitación personal.</em>','campaign_intro':'En lugar de enviar todas las prendas a todos, armá una campaña alrededor de una categoría y un grupo que eligió recibir novedades.',
        'campaign_message_title':'Hay novedades<br>que van con vos.','campaign_message':'Descubrí la nueva colección y consultá los beneficios de tu Club. Elegí tu próxima favorita desde el catálogo.','campaign_action':'Explorar la colección',
        'campaign_points':[('Un segmento claro','Compras anteriores o preferencias declaradas. Sin adivinar talles ni gustos.'),('Una colección concreta','Fotos, variantes y disponibilidad según el catálogo de tu local.'),('Un motivo propio','Acceso anticipado, un beneficio seleccionado o una atención para miembros: el descuento no es obligatorio.')],
        'campaign_cta':'Llevar mi próxima colección al Club','journey_title':'De una buena compra<br><em>a una relación con tu marca.</em>',
        'steps':[('Se lleva algo más que la prenda','La invitación al Club acompaña la compra, con el beneficio explicado en el local o por enlace.'),('Elige seguir en contacto','Guarda su tarjeta y autoriza los canales de novedades que se implementen.'),('Encuentra su próxima favorita','El mensaje conecta con una colección y una forma clara de consultar o pedir.')],
        'faqs':[('¿Necesito hacer descuentos para tener un Club?','No. Podés ofrecer acceso a novedades, beneficios seleccionados o atención para miembros. El programa se define con tu marca y el margen de tu negocio.'),('¿El catálogo puede mostrar talles y colores?','Sí. Las variantes se incluyen según la información que gestione tu tienda. La propuesta especifica si la disponibilidad se actualiza manualmente o mediante una integración.'),('¿Puedo recuperar clientes que no compran hace tiempo?','Podemos preparar campañas para clientes identificados que aceptaron recibir comunicaciones. El intervalo depende de tu categoría y temporada; no se considera perdido a todo cliente que no compra cada mes.')],
      },
      {
        **RETAIL_COMMON,'slug':'limpieza','path':'/limpieza/','name':'Comercios de limpieza','eyebrow':'IMAN para comercios de limpieza',
        'title':'Fidelización y reposición para comercios de limpieza | IMAN','description':'Convertí reposiciones en compras recurrentes con un Club en Wallet, campañas de email, combos y catálogo digital para tu comercio de limpieza.',
        'headline':'Cuando se termina,<br><em>que vuelvan<br>a tu negocio.</em>','intro':'Tus productos se usan todos los días. Conectá cada compra con la próxima reposición: beneficios, propuestas útiles y un catálogo fácil para volver a pedir.',
        'cta':'Quiero más compras recurrentes','hooks':['Reposición para hogar y comercio','Combos definidos por vos','Pedidos por producto y presentación'],
        'brand':'TU COMERCIO','art':'limpieza','product_category':'LIMPIEZA DEL HOGAR','product':'Todo para reponer','product_detail':'Productos y presentaciones bien claros.','product_action':'Armar mi pedido →','wallet_title':'Tu próxima<br>reposición suma.','notification_label':'TU COMERCIO · CLUB','notification':'¿Toca reponer lo de siempre?','notification_detail':'Mirá los productos y el beneficio de tu Club.',
        'uses_eyebrow':'Productos que vuelven a hacer falta','uses_title':'La reposición es habitual.<br><em>Tu negocio también puede serlo.</em>',
        'uses':[('Un Club para compras recurrentes','La tarjeta en Wallet reúne los beneficios del comercio. Definís cómo reconocer la frecuencia, las categorías o las compras identificadas.'),('Combos que respetan tu margen','Armá propuestas por necesidad: cocina, lavadero o un comercio. Elegís los productos, las cantidades y las condiciones.'),('Menos “¿cuál era el bidón?”','Catálogo con nombre, tamaño y presentación. El cliente elige y tu equipo recibe los productos y cantidades pedidos.')],
        'campaign_to':'DE TU COMERCIO, PARA SU CLUB','campaign_title':'La próxima reposición,<br><em>ya pensada.</em>','campaign_intro':'Un mensaje concreto puede recordar los productos habituales y proponer un combo útil, con un enlace directo al catálogo.',
        'campaign_message_title':'Que no te falte<br>lo de todos los días.','campaign_message':'Armá tu próxima reposición y consultá las propuestas del Club. Tus productos habituales, en un solo catálogo.','campaign_action':'Preparar mi reposición',
        'campaign_points':[('La necesidad','Compras del hogar y compras de un comercio pueden tener ritmos y presentaciones diferentes.'),('La propuesta','Combinás productos disponibles con precios y condiciones definidos por tu negocio.'),('La elección','El cliente revisa, cambia cantidades y confirma lo que necesita; el mensaje no crea una compra automática.')],
        'campaign_cta':'Crear mi campaña de recompra','journey_title':'Del bidón de hoy<br><em>al pedido que sigue.</em>',
        'steps':[('Se suma al Club','El beneficio se explica al comprar y la tarjeta queda a mano en Wallet.'),('Recibe una propuesta útil','La campaña se prepara según compras registradas y permisos de comunicación.'),('Arma la reposición','El catálogo ordena productos y cantidades para confirmar el pedido con tu equipo.')],
        'faqs':[('¿Sirve si vendo productos sueltos y envasados?','Podemos mostrar unidades, litros, envases y presentaciones. La forma de elegir cantidades, informar precios y confirmar disponibilidad se define para tu comercio.'),('¿Los combos se publican solos?','Se definen reglas de productos, margen y condiciones. Si incorporamos una automatización, acordamos qué propuestas prepara y cuáles requieren revisión antes de publicarse o enviarse.'),('¿Y si vendo principalmente por mayor?','Las listas por cliente, mínimos, bultos y reposición comercial tienen una propuesta específica. <a href="/limpieza/distribuidora/">Conocé IMAN para distribuidoras de limpieza</a>.')],
      },
      {
        **RETAIL_COMMON,'slug':'repuestos','path':'/repuestos/','name':'Repuestos y talleres','eyebrow':'IMAN para repuesteras y talleres',
        'title':'Fidelización y seguimiento para repuesteras y talleres | IMAN','description':'Conectá el próximo mantenimiento con tu taller o casa de repuestos: seguimiento de clientes, Wallet, email y catálogo con consultas de compatibilidad.',
        'headline':'El próximo service,<br><em>que empiece<br>con vos.</em>','intro':'Después de entregar el vehículo o vender el repuesto, la relación sigue. Organizá el seguimiento, los beneficios y la próxima consulta desde tu negocio.',
        'cta':'Quiero verlo en mi negocio','hooks':['Fechas definidas por tu equipo','Historial con contexto','Consulta de repuestos identificada'],
        'brand':'TU TALLER','art':'repuestos','product_category':'MANTENIMIENTO','product':'El próximo service','product_detail':'Producto, especificación y consulta de compatibilidad.','product_action':'Consultar este producto →','wallet_title':'Tu vehículo.<br>Tu taller de confianza.','notification_label':'TU TALLER · SEGUIMIENTO','notification':'¿Revisamos el próximo service?','notification_detail':'Consultá con tu taller y coordiná la visita.',
        'uses_eyebrow':'Hay trabajo después de entregar','uses_title':'El mantenimiento vuelve.<br><em>El cliente también.</em>',
        'uses':[('Historial que ayuda a atender','Vinculá cliente, trabajo realizado y datos del vehículo disponibles. El equipo tiene contexto para la próxima consulta.'),('Recordatorios con criterio','Tu taller define los intervalos y las reglas técnicas. El sistema organiza el aviso; no inventa diagnósticos ni plazos de mantenimiento.'),('Repuestos mejor identificados','El catálogo presenta códigos, variantes y especificaciones. Tu equipo valida compatibilidad antes de confirmar una compra.')],
        'campaign_to':'DE TU TALLER, PARA SUS CLIENTES','campaign_title':'Un recordatorio.<br><em>Una consulta bien atendida.</em>','campaign_intro':'Cuando llega una fecha de seguimiento definida por tu taller, el mensaje invita a revisar la necesidad y coordinar el siguiente paso.',
        'campaign_message_title':'Tu próximo service<br>merece una revisión.','campaign_message':'Contactanos para revisar el mantenimiento de tu vehículo y coordinar la atención que corresponda.','campaign_action':'Consultar con mi taller',
        'campaign_points':[('Un dato verificable','Fecha del trabajo y criterio registrado por tu equipo. El kilometraje se usa solo cuando está disponible y actualizado.'),('Un mensaje prudente','Invita a consultar; no afirma una falla ni recomienda una pieza sin revisión.'),('Un próximo paso','Consulta, presupuesto o turno según cómo atienda tu negocio.')],
        'campaign_cta':'Ordenar el seguimiento de mis clientes','journey_title':'De un trabajo resuelto<br><em>al próximo contacto.</em>',
        'steps':[('Se registra el trabajo','Cliente, vehículo y servicio se vinculan según el sistema y la información disponibles.'),('Se define el seguimiento','El taller establece fecha, criterio y canal autorizado para el recordatorio.'),('El cliente consulta','Tu equipo revisa el caso y confirma presupuesto, compatibilidad o atención.')],
        'faqs':[('¿El sistema recomienda cuándo hacer cada mantenimiento?','Los intervalos y criterios los define tu taller con información técnica y datos del vehículo. IMAN organiza el seguimiento de esas reglas; no reemplaza la evaluación profesional.'),('¿Se pueden pedir repuestos desde el catálogo?','Sí, con los campos necesarios para identificar producto y variante. La compatibilidad y la disponibilidad se validan antes de confirmar el pedido.'),('¿Puedo conectar el seguimiento con turnos?','Sí. El circuito puede llevar a una consulta o agenda. La integración con la herramienta que use tu taller se define en la propuesta.')],
      },
    ]
    wholesale_base = {
      'kind':'wholesale','service':'Catálogos y pedidos mayoristas con automatización de compras','contact_service':'IMAN Comercios',
      'strip_title':'De la lista de productos al pedido completo.', 'channels':['Catálogo mayorista','Condiciones por cliente','Reposición','Compras automatizadas'],
      'campaign_eyebrow':'Una cartera que vuelve a pedir','platform_note':'Las integraciones, reglas de compra y aprobaciones se acuerdan por proyecto. Una propuesta preparada por el sistema no confirma una compra ni ejecuta un pago.',
      'journey_eyebrow':'Del comercio a tu operación','related_eyebrow':'Catálogo y operación, conectados',
      'related_title':'El pedido se arma.<br>El proceso sigue.',
      'related':[('IMAN Comercios','Tu catálogo, clientes y condiciones mayoristas.','/comercios/'),('IMAN Automatizaciones','Validación de pedidos, compras y seguimiento.','/automatizaciones/#compras')],
    }
    data += [
      {
        **wholesale_base,'slug':'distribuidoras','path':'/distribuidoras/','name':'Distribuidoras','eyebrow':'IMAN para distribuidoras',
        'title':'Catálogos y pedidos mayoristas para distribuidoras | IMAN','description':'Catálogo mayorista con condiciones por cliente, pedidos completos y seguimiento de cartera. Conectá tu distribuidora con automatizaciones de compras.',
        'headline':'Que comprar por mayor<br><em>sea más simple.</em>','intro':'Tu catálogo, tus listas y cada pedido en un mismo recorrido. Facilitá la reposición de tus comercios y conectá la venta con las reglas de tu operación.',
        'cta':'Quiero mi catálogo mayorista','hooks':['Presentaciones y mínimos claros','Condiciones por comercio','Compras con reglas y aprobación'],
        'art':'box','board_customer':'Comercio de ejemplo · Lista asignada','order_rows':[('Producto de línea','Caja × 12 unidades','2 cajas'),('Reposición habitual','Bulto × 6 unidades','3 bultos'),('Producto complementario','Unidad comercial','4 unid.')],
        'board_note_label':'PEDIDO ESTRUCTURADO','board_note':'Producto, cantidad y condición.','board_note_detail':'Tu equipo revisa antes de confirmar.',
        'uses_eyebrow':'Menos traducción de mensajes a pedidos','uses_title':'Cada comercio, su lista.<br><em>Cada pedido, completo.</em>',
        'uses':[('Un catálogo que sabe vender por mayor','Productos, presentaciones, mínimos y listas asignadas. El comercio entiende qué está pidiendo y bajo qué condiciones.'),('Reposición sin empezar de cero','Un recorrido para consultar productos habituales y armar el siguiente pedido. Cantidades y condiciones quedan identificadas.'),('La compra conectada a tu operación','Validaciones, registro y seguimiento según tus sistemas. Un agente puede preparar propuestas dentro de límites definidos, con revisión donde corresponda.')],
        'campaign_to':'PARA UN COMERCIO DE TU CARTERA','campaign_title':'Tu próxima venta<br><em>ya conoce al cliente.</em>','campaign_intro':'Usá el historial para preparar una propuesta de reposición. El comercio revisa lo que necesita y tu equipo confirma las condiciones vigentes.',
        'campaign_message_title':'Armemos la próxima<br>reposición.','campaign_message':'Revisá tus productos habituales y completá el pedido según lo que necesitás esta vez.',
        'proposal_items':['Productos habituales identificados','Cantidades editables por el comercio','Condiciones vigentes para revisar'],
        'campaign_points':[('El comercio','Historial, lista y relación comercial en contexto.'),('La propuesta','Productos y cantidades preparados para revisar, sin comprometer stock ni precios desactualizados.'),('La confirmación','Aprobación comercial y registro del pedido según tus reglas.')],
        'campaign_cta':'Conectar catálogo y reposición','journey_title':'De “pasame la lista”<br><em>a “este es mi pedido”.</em>',
        'steps':[('Consulta su catálogo','El cliente accede a los productos y condiciones que le correspondan.'),('Arma el pedido','Selecciona presentaciones y cantidades, con los datos que necesita tu equipo.'),('Tu operación lo recibe','Se revisan disponibilidad, condiciones y excepciones antes de confirmar.')],
        'faqs':[('¿Cada cliente puede tener una lista diferente?','Sí. La propuesta puede incluir listas, condiciones y acceso por cliente. Definimos quién actualiza esos datos y cómo se evita mostrar condiciones a quien no corresponde.'),('¿Se conecta con mi sistema de gestión?','Evaluamos las interfaces disponibles: API, archivos u otro mecanismo autorizado. La propuesta precisa qué se sincroniza, cada cuánto y cómo se resuelven errores.'),('¿La automatización puede comprar sin consultarme?','Solo se implementan acciones dentro de reglas y autorizaciones expresas. El alcance distingue preparar una propuesta, aprobar un pedido, confirmarlo y pagar; no se supone autorización para todas esas etapas.')],
      },
      {
        **wholesale_base,'slug':'distribuidora-pet','path':'/petshops/distribuidora/','name':'Distribuidoras pet','eyebrow':'IMAN para distribuidoras pet',
        'title':'Catálogo mayorista y reposición para distribuidoras pet | IMAN','description':'Ordená pedidos de pet shops y forrajerías con catálogo mayorista, marcas, presentaciones, listas por comercio y automatización de reposición.',
        'headline':'Más fácil reponer.<br><em>Más motivos<br>para elegirte.</em>','intro':'Marcas, líneas y tamaños de bolsa, sin perderse entre mensajes. Dale a cada pet shop un catálogo con sus condiciones y un recorrido claro para volver a pedir.',
        'cta':'Quiero verlo en mi distribuidora','hooks':['Marca, línea y bolsa identificadas','Listas por pet shop','Reposición y compras conectadas'],
        'art':'pet','board_customer':'Pet shop de ejemplo · Lista minoristas','order_rows':[('Alimento adulto','Presentación: bolsa × 15 kg','8 bolsas'),('Alimento cachorro','Presentación: bolsa × 3 kg','6 bolsas'),('Accesorios de línea','Presentación: pack comercial','2 packs')],
        'board_note_label':'CADA PRESENTACIÓN, CLARA','board_note':'La bolsa correcta, en el pedido.','board_note_detail':'Marca, línea y cantidad para revisar.',
        'uses_eyebrow':'Tu catálogo, con lógica pet','uses_title':'No es “mandame alimento”.<br><em>Es un pedido preciso.</em>',
        'uses':[('El catálogo que necesita un pet shop','Marca, especie, línea y tamaño de bolsa. Presentaciones claras y condiciones asignadas al comercio.'),('Una cartera con ritmo propio','Seguimiento por comercios y familias de productos: quién repone, quién cambió su frecuencia y qué propuesta conviene revisar.'),('Compras mayoristas con límites','Preparación de reposiciones y validaciones según stock, condiciones y presupuesto disponibles. Las sustituciones y la compra requieren las reglas acordadas.')],
        'campaign_to':'PARA UN PET SHOP DE TU CARTERA','campaign_title':'Que la próxima reposición<br><em>empiece en tu catálogo.</em>','campaign_intro':'Una propuesta útil conserva el contexto del pet shop: líneas que trabaja, presentaciones y condiciones. El comercio elige qué reponer esta vez.',
        'campaign_message_title':'Tus líneas habituales.<br>Tu próxima reposición.','campaign_message':'Revisá marcas y presentaciones para completar el pedido de tu pet shop.',
        'proposal_items':['Marca, línea y tamaño de bolsa','Cantidades que revisa el pet shop','Lista y condiciones del comercio'],
        'campaign_points':[('Por línea y presentación','Sin mezclar variedades o tamaños que tengan usos comerciales distintos.'),('Por comercio','La propuesta respeta su lista y su historial, sin aplicar una frecuencia igual para todos.'),('Con validación','Tu equipo confirma disponibilidad y cualquier alternativa antes de cerrar el pedido.')],
        'campaign_cta':'Armar mi circuito de reposición','journey_title':'Del pet shop<br><em>a tu próximo despacho.</em>',
        'steps':[('Encuentra la línea','El comercio filtra el catálogo por las marcas y presentaciones que necesita.'),('Revisa su reposición','Elige cantidades y consulta las condiciones asignadas a su cuenta.'),('Se confirma y prepara','Tu equipo valida el pedido y lo deriva al circuito de preparación acordado.')],
        'faqs':[('¿El catálogo distingue las distintas bolsas de una misma línea?','Sí. Marca, variedad, peso y unidad comercial se modelan para evitar ambigüedades. Cada presentación puede tener código y condiciones propios.'),('¿Puedo separar listas de pet shops y forrajerías?','Sí. El acceso, los precios y las condiciones pueden asignarse por cliente o grupo, según la información comercial que gestione tu distribuidora.'),('¿También ofrecen fidelización para el pet shop?','Sí. <a href="/pet/">IMAN para pet shops</a> trabaja la relación del comercio con el consumidor final. El catálogo mayorista y sus condiciones permanecen en el circuito de la distribuidora.')],
      },
      {
        **wholesale_base,'slug':'distribuidora-limpieza','path':'/limpieza/distribuidora/','name':'Distribuidoras de limpieza','eyebrow':'IMAN para distribuidoras de limpieza',
        'title':'Catálogo mayorista para distribuidoras de limpieza | IMAN','description':'Catálogo por unidades, bidones y bultos; listas por cliente y pedidos estructurados para distribuidoras de limpieza. Reposición y compras automatizadas.',
        'headline':'Bidones, bultos,<br>condiciones.<br><em>Todo en su lugar.</em>','intro':'Tus clientes pueden reponer sin reconstruir cada pedido por mensaje. Un catálogo mayorista con presentaciones claras, sus condiciones y la conexión con tu operación.',
        'cta':'Quiero ordenar mis pedidos','hooks':['Unidades y presentaciones claras','Listas por comercio','Reposición con revisión comercial'],
        'art':'limpieza','board_customer':'Comercio de ejemplo · Lista mayorista','order_rows':[('Limpiador multiuso','Presentación: bidón × 5 L','6 bidones'),('Detergente','Presentación: caja × 4 bidones','2 cajas'),('Accesorios de limpieza','Presentación: bulto comercial','3 bultos')],
        'board_note_label':'SIN ADIVINAR CANTIDADES','board_note':'No es lo mismo caja que bidón.','board_note_detail':'Cada unidad comercial queda identificada.',
        'uses_eyebrow':'Una operación que entiende tus productos','uses_title':'El detalle del pedido<br><em>hace la diferencia.</em>',
        'uses':[('Cada presentación, sin dudas','Unidades, litros, bidones, cajas y bultos con su equivalencia comercial. Se muestra qué puede pedir cada cliente.'),('Condiciones para cada relación','Listas, mínimos y reglas por comercio o segmento. Tu equipo conserva el control de las condiciones vigentes.'),('La reposición, conectada','Propuestas por historial y validaciones antes de registrar el pedido. Los flujos pueden conectar catálogo, administración y compras según tus sistemas.')],
        'campaign_to':'PARA UN CLIENTE MAYORISTA','campaign_title':'Una propuesta de reposición.<br><em>Sin rehacer la lista.</em>','campaign_intro':'Usá las familias y presentaciones del historial para preparar un pedido revisable. El cliente ajusta cantidades y tu equipo confirma condiciones.',
        'campaign_message_title':'Reponé lo habitual.<br>Ajustá lo que cambió.','campaign_message':'Revisá productos, presentaciones y cantidades para armar el próximo pedido de tu comercio.',
        'proposal_items':['Unidad comercial explícita','Cantidades revisables por producto','Condiciones sujetas a confirmación'],
        'campaign_points':[('La unidad correcta','Caja, bidón o unidad: el pedido deja claro qué se está solicitando.'),('El contexto comercial','Lista y mínimos correspondientes al cliente, con vigencias definidas.'),('El control antes del despacho','Disponibilidad, equivalencias y condiciones se validan antes de confirmar.')],
        'campaign_cta':'Conectar mis pedidos mayoristas','journey_title':'De la reposición<br><em>al pedido listo para revisar.</em>',
        'steps':[('Consulta su lista','El cliente ve los productos y condiciones asignados a su comercio.'),('Elige presentaciones','Arma las cantidades en la unidad comercial correcta.'),('Tu equipo valida','Se revisan stock, condiciones y excepciones antes de pasar a preparación.')],
        'faqs':[('¿Puedo vender por unidad, bidón y caja en el mismo catálogo?','Sí. Se definen las presentaciones y sus equivalencias para que el pedido no mezcle unidades de forma ambigua. Los precios y mínimos se aplican según las reglas acordadas.'),('¿Las condiciones pueden cambiar según el cliente?','Sí. El proyecto puede incluir listas, mínimos y reglas por cliente o grupo. Definimos quién mantiene esas condiciones y cómo se actualizan.'),('¿Qué pasa si un producto no está disponible?','El flujo debe identificar el faltante y derivar la excepción. Las sustituciones, cambios de cantidad y condiciones requieren las reglas de aprobación acordadas con tu equipo.')],
      },
      {
        'kind':'transport','slug':'transporte','path':'/transporte/','name':'Transporte y reparto','eyebrow':'IMAN para transporte y reparto',
        'title':'Automatización de avisos para transporte y reparto | IMAN','description':'Comunicá cada etapa confirmada del pedido y organizá las excepciones. Automatización de seguimiento y avisos para transporte, reparto y logística.',
        'service':'Automatización de avisos y seguimiento de transporte','contact_service':'IMAN Automatizaciones',
        'headline':'El pedido avanza.<br><em>Tu cliente<br>se entera.</em>','intro':'Convertí los estados de tu operación en avisos útiles. Preparado, en reparto, entregado: cada evento confirmado dispara el próximo paso que corresponde.',
        'cta':'Quiero automatizar mis avisos','hooks':['Etapas que tu equipo confirma','Mensajes con contexto del pedido','Excepciones con responsable'],
        'strip_title':'Una entrega con información en cada etapa.','channels':['Estados del pedido','Avisos al cliente','Registro de envíos','Gestión de excepciones'],
        'uses_eyebrow':'Menos consultas de seguimiento repetidas','uses_title':'La información existe.<br><em>Hagamos que llegue.</em>',
        'uses':[('Un estado que dice algo','Definimos etapas reales de tu operación, con un identificador de pedido y una fuente que confirme cada cambio.'),('El aviso correcto','El mensaje incluye el estado y el próximo paso. Se envía por el canal acordado, con contacto autorizado y registro de entrega disponible.'),('Las excepciones, visibles','Dirección incompleta, demora o intento fallido: el caso se deriva a una persona, con motivo y datos para resolverlo.')],
        'campaign_eyebrow':'Cuando una entrega necesita una persona','campaign_title':'Si algo se traba,<br><em>que no se pierda.</em>','campaign_intro':'Automatizar también es detectar cuándo el flujo debe detenerse. La información incompleta llega al equipo responsable, en lugar de generar un aviso engañoso al cliente.',
        'campaign_points':[('El pedido identificado','Cada caso conserva la referencia de la entrega y el cambio que lo originó.'),('El motivo a la vista','Una excepción concreta y un próximo paso, sin obligar al equipo a reconstruir toda la conversación.'),('El seguimiento','Registro de la revisión y reanudación del circuito cuando se corrige la información.')],
        'campaign_cta':'Revisar mi circuito de entregas','platform_note':'Los avisos reflejan datos confirmados. El seguimiento GPS en vivo, las estimaciones horarias y cada integración requieren un alcance específico.',
        'journey_eyebrow':'Del depósito al destinatario','journey_title':'Un evento confirmado.<br><em>Un próximo paso claro.</em>',
        'steps':[('Tu operación cambia el estado','Desde el sistema o el registro que se integre: preparado, despachado o en reparto.'),('El flujo valida y comunica','Revisa los datos necesarios y prepara el aviso correspondiente, evitando duplicados según las reglas acordadas.'),('Tu equipo ve el resultado','Consulta el registro y atiende las excepciones que necesitan intervención.')],
        'related_eyebrow':'Una automatización con principio y fin','related_title':'Conectá los avisos<br>con el resto del proceso.',
        'related':[('IMAN Automatizaciones','Registro, validaciones, comunicaciones y control de errores.','/automatizaciones/'),('Catálogos y pedidos','Organizá el pedido antes de que entre al reparto.','/comercios/')],
        'faqs':[('¿Incluye seguimiento GPS en vivo?','Esta propuesta se centra en etapas confirmadas del pedido. El GPS en vivo requiere una fuente de ubicación, permisos y un desarrollo específico; no se presenta como incluido por defecto.'),('¿Por qué canal se envían los avisos?','Puede implementarse el canal que corresponda a tu operación y a los permisos del destinatario. Se acuerdan proveedor, plantillas, costos y límites antes de activar el envío.'),('¿Qué pasa si un aviso falla o se repite el evento?','El diseño contempla identificación del evento, registro, reintentos y derivación de errores según el proveedor. Las reglas se prueban con los casos reales del circuito antes de activarlo.')],
      },
    ]
    return {d['path']: {'title':d['title'],'description':d['description'],'body':body(d),'faqs':d['faqs'],'service':d['service'],'contact_service':d['contact_service']} for d in data}
