export const CALENDLY_URL = 'https://calendly.com/santiago-iman/30min';
export const escapeHTML = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const E=escapeHTML;
const serviceList=lead => lead.servicios?.length ? lead.servicios : [lead.servicio || 'Quiero que me orienten'];
const paragraph=text=>`<p style="font-size:15px;line-height:1.75;color:#d2cfc6;margin:0 0 20px">${text}</p>`;
const heading=text=>`<h1 style="font-family:'Arial Narrow',Arial,Helvetica,sans-serif;font-size:38px;font-weight:400;line-height:1.12;letter-spacing:-1px;margin:24px 0;color:#eeeae1">${text}</h1>`;
const eyebrow=text=>`<p style="margin:0 0 18px;font-family:'Courier New',monospace;font-size:10px;letter-spacing:1.5px;color:#75cedd">${text}</p>`;
function button(label,url){return `<table role="presentation" cellspacing="0" cellpadding="0" style="margin:26px 0"><tr><td align="center" bgcolor="#eeeae1" style="background-color:#eeeae1;border:1px solid #eeeae1;mso-padding-alt:16px 24px"><a href="${E(url)}" style="display:inline-block;padding:16px 24px;mso-padding-alt:0;color:#242424;font-size:14px;font-family:Arial,Helvetica,sans-serif;font-weight:400;text-decoration:none;line-height:20px">${label}</a></td></tr></table>`;}
function frame(preheader,body,footer='Este correo responde a una consulta realizada en iman.ar. No te suscribimos a una lista.'){
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><meta name="supported-color-schemes" content="dark"><title>IMAN · Tecnología a medida</title><style>@media screen and (max-width:480px){.email-pad{padding:26px 20px!important}.email-title{font-size:32px!important}}</style></head><body bgcolor="#242424" style="margin:0;background-color:#242424;color:#eeeae1;font-family:Arial,Helvetica,sans-serif;-webkit-text-size-adjust:100%"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;mso-hide:all">${E(preheader)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" bgcolor="#242424"><tr><td align="center" style="padding:24px 12px"><!--[if mso]><table role="presentation" width="600"><tr><td><![endif]--><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background-color:#272727;border:1px solid #50504c"><tr><td class="email-pad" style="padding:30px 34px;border-bottom:1px solid #50504c"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td width="68"><a href="https://www.iman.ar/"><img src="https://www.iman.ar/assets/brand-email.png" alt="IMAN" width="52" height="52" style="display:block;border:0;width:52px;height:52px"></a></td><td><a href="https://www.iman.ar/" style="font-family:'Arial Narrow',Arial,sans-serif;font-size:34px;font-weight:400;letter-spacing:2px;color:#eeeae1;text-decoration:none">IMAN<span style="color:#75cedd">·</span></a></td><td align="right" style="font-family:'Courier New',monospace;font-size:9px;line-height:1.8;letter-spacing:1px;color:#b9b7af">TECNOLOGÍA A MEDIDA<br>ARGENTINA</td></tr></table></td></tr><tr><td class="email-pad" style="padding:36px 34px">${body}</td></tr><tr><td class="email-pad" style="padding:24px 34px;border-top:1px solid #50504c;font-size:11px;line-height:1.7;color:#b9b7af">${footer}<br><a href="https://www.iman.ar/privacidad/" style="color:#d2cfc6;text-decoration:underline">Privacidad</a> · IMAN</td></tr></table><!--[if mso]></td></tr></table><![endif]--></td></tr></table></body></html>`;
}
export function confirmationEmail(lead){
  const services=serviceList(lead);
  return {
    subject:'Recibimos tu consulta · El próximo paso con IMAN',
    text:`Hola, ${lead.nombre}.\n\nGracias por contarnos sobre ${lead.negocio}. Recibimos tu consulta.\n\nServicios elegidos:\n${services.map(s=>'- '+s).join('\n')}\n\nVamos a revisar tu consulta y contactarte para entender tu negocio y definir una propuesta a medida.\n\nSi preferís, elegí un horario para conversar con Santiago:\n${CALENDLY_URL}\n\nVemos cómo trabajás hoy, qué querés mejorar y cuál puede ser una primera implementación útil. También podés responder a este correo.\n\nSantiago · IMAN\nhttps://www.iman.ar/\n\nEsta consulta no te suscribe a marketing.\nPrivacidad: https://www.iman.ar/privacidad/`,
    html:frame('Recibimos tu consulta. Definamos un próximo paso para tu negocio.',eyebrow('CONSULTA / RECIBIDA')+heading('El próximo paso<br>lo damos juntos.')+paragraph(`Hola, ${E(lead.nombre)}. Gracias por contarnos sobre <span style="color:#eeeae1">${E(lead.negocio)}</span>.`)+`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-top:1px solid #50504c;border-bottom:1px solid #50504c;margin:24px 0"><tr><td style="padding:20px 0">${eyebrow('TU PUNTO DE PARTIDA')}${services.map((s,i)=>`<p style="margin:9px 0;color:#eeeae1;font-size:15px;line-height:1.5"><span style="font-family:'Courier New',monospace;font-size:10px;color:#75cedd">0${i+1}&nbsp;&nbsp;</span>${E(s)}</p>`).join('')}</td></tr></table>`+paragraph('Vamos a revisar tu consulta y contactarte para entender tu negocio y definir una propuesta a medida.')+paragraph('Si preferís, elegí un horario con Santiago. Vemos cómo trabajás hoy y cuál puede ser una primera implementación útil.')+button('Elegir un horario',CALENDLY_URL)+paragraph('También podés responder a este correo y contarnos un poco más.')+`<p style="margin:28px 0 0;color:#eeeae1;font-size:14px;line-height:1.8">Santiago<br><span style="font-size:11px;color:#b9b7af">IMAN · A medida. Con vos.</span></p>`)
  };
}
export function ownerEmail(lead){
  const services=serviceList(lead);
  const fields=[['Nombre',lead.nombre],['Negocio',lead.negocio],['Rubro',lead.rubro||'No indicado'],['Ciudad',lead.ciudad||'No indicada'],['Servicios',services.join('\n')],['Email',lead.email],['WhatsApp',lead.whatsapp||'No indicado'],['Consulta',lead.comentario||'Sin comentario adicional'],['Página',lead.source||'No indicada'],...Object.entries(lead.utm||{}).map(([k,v])=>[k,v])];
  return {
    subject:`Nueva consulta IMAN · ${lead.negocio}`,
    text:`Nueva consulta desde iman.ar\n\n${fields.map(([k,v])=>`${k}: ${v}`).join('\n')}\n\nAutorizó recibir una respuesta a su consulta. Respondé este correo para contactar al cliente. No es una suscripción a marketing.`,
    html:frame('Nueva consulta de un negocio desde iman.ar.',eyebrow('CONTACTO / NUEVA CONSULTA')+heading('Un negocio.<br>Una posibilidad.')+`<table role="presentation" width="100%" cellspacing="0" cellpadding="0">${fields.map(([k,v])=>`<tr><td style="padding:14px 0;border-bottom:1px solid #50504c;vertical-align:top;width:90px;font-size:11px;color:#b9b7af">${E(k)}</td><td style="padding:14px 0 14px 12px;border-bottom:1px solid #50504c;font-size:14px;line-height:1.65;color:#eeeae1;word-break:break-word;white-space:pre-wrap">${E(v)}</td></tr>`).join('')}</table>`+button('Responder la consulta','mailto:'+lead.email)+paragraph('Revisá los servicios elegidos y proponé un primer paso acotado. La persona autorizó una respuesta comercial, no una suscripción.'),'Notificación interna de una consulta recibida en iman.ar.')
  };
}
export function newsletterEmail(person,confirmationURL,unsubscribeURL){return {
  subject:'Un paso más para recibir ideas de IMAN',
  text:`Hola, ${person.nombre}.\n\nPediste recibir ideas para que tus clientes vuelvan. Confirmá tu email para sumarte:\n${confirmationURL}\n\nVas a recibir ideas de fidelización, comunicación y automatización para comercios. Podés darte de baja cuando quieras. Este enlace vence en 48 horas.\n\nSi no lo solicitaste, ignorá este correo: no te vamos a suscribir. También podés cancelar la solicitud:\n${unsubscribeURL}\n\nIMAN · https://www.iman.ar/`,
  html:frame('Confirmá tu email para recibir ideas de IMAN.',eyebrow('IDEAS / PARA TU COMERCIO')+heading('Clientes que vuelven.<br>Ideas que ayudan.')+paragraph(`Hola, ${E(person.nombre)}. Confirmá tu email para recibir ideas de fidelización, comunicación y automatización para tu comercio.`)+button('Confirmar mi email',confirmationURL)+paragraph('Este enlace vence en 48 horas. Podés darte de baja cuando quieras.'),`Recibís este mensaje porque se solicitó una suscripción en iman.ar. Si no fuiste vos, ignoralo: no te vamos a suscribir. <a href="${E(unsubscribeURL)}" style="color:#d2cfc6">Cancelar solicitud</a>.`)
};}
export function newsletterWelcomeEmail(person,unsubscribeURL){
  const resourceURL='https://www.iman.ar/recursos/recuperar-clientes/';
  const ideas=[['Dale un motivo para volver.','Ofrecé un beneficio concreto en la próxima compra, con una condición fácil de entender.'],['Elegí el momento.','Separá a quienes compraron hace poco de quienes hace tiempo no vuelven antes de mandar el mismo mensaje a todos.'],['Medí la segunda compra.','Mirá cuántos clientes regresan y qué propuesta los trae de nuevo.']];
  return {subject:'Bienvenido a IMAN · Tres ideas para que tus clientes vuelvan',text:`Hola, ${person.nombre}.\n\nTu suscripción está confirmada. Para empezar:\n\n${ideas.map(([h,p],i)=>`${i+1}. ${h} ${p}`).join('\n\n')}\n\nLeé la guía: ${resourceURL}\n\nSantiago · IMAN\n\nPodés darte de baja: ${unsubscribeURL}`,html:frame('Tu suscripción está confirmada. Empezamos con tres ideas.',eyebrow('IDEAS / BIENVENIDO A IMAN')+heading('Hagamos que<br>vuelvan.')+paragraph(`Hola, ${E(person.nombre)}. Tu suscripción está confirmada. Para empezar, tres ideas que podés llevar a tu comercio:`)+ideas.map(([h,p],i)=>`<div style="border-bottom:1px solid #50504c;padding:20px 0">${eyebrow('0'+(i+1))}<h2 style="color:#eeeae1;font-size:19px;font-weight:400;margin:0 0 12px">${h}</h2>${paragraph(p)}</div>`).join('')+button('Leer la guía completa',resourceURL)+paragraph('Gracias por sumarte.<br>Santiago · IMAN'),`Recibís este mensaje porque confirmaste tu suscripción. <a href="${E(unsubscribeURL)}" style="color:#d2cfc6">Darte de baja</a>.`)};
}
