export const CALENDLY_URL = 'https://calendly.com/santiago-iman/30min';

export const escapeHTML = (value) => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

function frame(preheader, body, footer = 'Este correo responde a una consulta realizada en iman.ar. No te suscribimos a una lista.') {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>IMAN · Tecnología que acerca</title></head><body style="margin:0;background:#f4f5fb;color:#161625;font-family:Arial,Helvetica,sans-serif;-webkit-text-size-adjust:100%"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent">${escapeHTML(preheader)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f5fb"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" style="width:100%;max-width:600px;background:#fff;border:1px solid #e5e6ef;border-radius:24px;overflow:hidden"><tr><td style="padding:32px 32px 24px;border-bottom:1px solid #ececf3"><a href="https://www.iman.ar/" style="color:#4F46F5;text-decoration:none;font-size:28px;font-weight:900;letter-spacing:-1.3px">IMAN<span style="color:#151523">.</span></a><p style="margin:8px 0 0;color:#69697b;font-size:12px;letter-spacing:1.5px;text-transform:uppercase">Tecnología que acerca</p></td></tr>${body}<tr><td style="padding:24px 32px;background:#fafafe;border-top:1px solid #ececf3;font-size:12px;color:#777789;line-height:1.6">${footer}<br><a href="https://www.iman.ar/privacidad/" style="color:#656575;text-decoration:underline">Privacidad</a> · IMAN</td></tr></table></td></tr></table></body></html>`;
}

export function newsletterEmail(person, confirmationURL, unsubscribeURL) {
  return {
    subject: 'Un paso más para recibir ideas de IMAN',
    text: `Hola, ${person.nombre}.\n\nPediste recibir ideas para que tus clientes vuelvan. Confirmá tu email para sumarte:\n${confirmationURL}\n\nVas a recibir ideas de fidelización, comunicación y automatización para comercios. Podés darte de baja cuando quieras. Este enlace vence en 48 horas.\n\nSi no lo solicitaste, ignorá este correo: no te vamos a suscribir. También podés cancelar la solicitud:\n${unsubscribeURL}\n\nIMAN · https://www.iman.ar/`,
    html: frame('Confirmá tu email para recibir ideas de IMAN.',`<tr><td style="padding:36px 32px"><span style="display:inline-block;border:1px solid #dddafe;border-radius:30px;padding:7px 12px;color:#4F46F5;background:#f4f2ff;font-size:12px;font-weight:700">IDEAS PARA TU COMERCIO</span><h1 style="font-size:32px;line-height:1.15;letter-spacing:-1px;margin:22px 0;color:#171726">Clientes que vuelven.<br>Ideas que ayudan.</h1><p style="font-size:16px;line-height:1.65;color:#56566d">Hola, ${escapeHTML(person.nombre)}. Confirmá tu email para recibir ideas de fidelización, comunicación y automatización para tu comercio.</p><table role="presentation" cellspacing="0" cellpadding="0" style="margin:24px 0"><tr><td bgcolor="#4F46F5" style="border-radius:10px"><a href="${escapeHTML(confirmationURL)}" style="display:inline-block;padding:17px 25px;color:#fff;font-size:15px;font-weight:700;text-decoration:none;border:1px solid #4F46F5;border-radius:10px">Confirmar mi email&nbsp; →</a></td></tr></table><p style="font-size:13px;line-height:1.6;color:#777789">Este enlace vence en 48 horas. Podés darte de baja cuando quieras.</p></td></tr>`,`Recibís este mensaje porque se solicitó una suscripción en iman.ar. Si no fuiste vos, ignoralo: no te vamos a suscribir. <a href="${escapeHTML(unsubscribeURL)}" style="color:#656575;text-decoration:underline">Cancelar solicitud</a>.`)
  };
}

export function newsletterWelcomeEmail(person, unsubscribeURL) {
  const resourceURL='https://www.iman.ar/recursos/recuperar-clientes/';
  return {
    subject:'Bienvenido a IMAN · Tres ideas para que tus clientes vuelvan',
    text:`Hola, ${person.nombre}.\n\nTu suscripción a las ideas de IMAN está confirmada. Para empezar, tres acciones sencillas:\n\n1. Dale un motivo para volver. Ofrecé un beneficio concreto en la próxima compra, con una condición fácil de entender.\n2. Elegí el momento. Separá a quienes compraron hace poco de quienes hace tiempo no vuelven antes de mandar el mismo mensaje a todos.\n3. Medí la segunda compra. Mirá cuántos clientes regresan y qué propuesta los trae de nuevo.\n\nLeé la guía para recuperar clientes: ${resourceURL}\n\nGracias por sumarte.\nSantiago · IMAN\n\nPodés darte de baja cuando quieras: ${unsubscribeURL}`,
    html:frame('Tu suscripción está confirmada. Empezamos con tres ideas para tu comercio.',`<tr><td style="padding:36px 32px"><span style="display:inline-block;border:1px solid #dddafe;border-radius:30px;padding:7px 12px;color:#4F46F5;background:#f4f2ff;font-size:12px;font-weight:700">BIENVENIDO A IMAN</span><h1 style="font-size:32px;line-height:1.15;letter-spacing:-1px;margin:22px 0;color:#171726">Hagamos que<br>vuelvan.</h1><p style="font-size:16px;line-height:1.65;color:#56566d">Hola, ${escapeHTML(person.nombre)}. Tu suscripción está confirmada. Para empezar, tres ideas que podés llevar a tu comercio:</p>${[['01','Dale un motivo para volver.','Ofrecé un beneficio concreto en la próxima compra, con una condición fácil de entender.'],['02','Elegí el momento.','Separá a quienes compraron hace poco de quienes hace tiempo no vuelven antes de mandar el mismo mensaje a todos.'],['03','Medí la segunda compra.','Mirá cuántos clientes regresan y qué propuesta los trae de nuevo.']].map(([n,title,body])=>`<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin-top:16px;border-bottom:1px solid #ececf3"><tr><td style="width:34px;padding:0 14px 20px 0;vertical-align:top;color:#4F46F5;font-weight:700;font-size:15px">${n}</td><td style="padding-bottom:20px"><strong style="font-size:16px;color:#242436">${title}</strong><p style="font-size:14px;line-height:1.65;color:#66667b;margin:6px 0 0">${body}</p></td></tr></table>`).join('')}<table role="presentation" cellspacing="0" cellpadding="0" style="margin:26px 0"><tr><td bgcolor="#4F46F5" style="border-radius:10px"><a href="${resourceURL}" style="display:inline-block;padding:17px 25px;color:#fff;font-size:15px;font-weight:700;text-decoration:none;border:1px solid #4F46F5;border-radius:10px">Leer la guía completa&nbsp; →</a></td></tr></table><p style="font-size:15px;line-height:1.7;margin:0;color:#242436">Gracias por sumarte.<br><strong>Santiago · IMAN</strong></p></td></tr>`,`Recibís este mensaje de bienvenida porque confirmaste tu suscripción en iman.ar. <a href="${escapeHTML(unsubscribeURL)}" style="color:#656575;text-decoration:underline">Darte de baja</a>.`)
  };
}

export function confirmationEmail(lead) {
  const name = escapeHTML(lead.nombre);
  const business = escapeHTML(lead.negocio);
  const service = escapeHTML(lead.servicio);
  return {
    subject: 'Recibimos tu consulta · Demos el próximo paso con IMAN',
    text: `Hola, ${lead.nombre}.\n\nGracias por contarnos sobre ${lead.negocio}. Recibimos tu consulta por ${lead.servicio} y vamos a revisarla para proponerte un próximo paso concreto.\n\nSi querés avanzar ahora, podés elegir un horario para conversar con Santiago:\n${CALENDLY_URL}\n\nEn la charla vemos cómo trabajás hoy, qué querés mejorar y cuál puede ser una primera implementación útil para tu negocio.\n\nTambién podés responder a este correo y sumar lo que necesites.\n\nSantiago · IMAN\nhttps://www.iman.ar/\n\nRecibís este correo porque enviaste una consulta en iman.ar. No te suscribimos a una lista.\nPrivacidad: https://www.iman.ar/privacidad/`,
    html: frame('Tu consulta ya llegó. Podés elegir un horario para conversar con Santiago.', `<tr><td style="padding:36px 32px 0"><span style="display:inline-block;border:1px solid #dddafe;border-radius:30px;padding:7px 12px;color:#4F46F5;background:#f4f2ff;font-size:12px;font-weight:700">CONSULTA RECIBIDA</span><h1 style="font-size:34px;line-height:1.12;letter-spacing:-1.2px;margin:22px 0 20px;color:#171726">El próximo paso<br>lo damos juntos.</h1><p style="font-size:16px;line-height:1.65;margin:0 0 16px">Hola, ${name}.</p><p style="font-size:16px;line-height:1.65;color:#56566d;margin:0 0 24px">Gracias por contarnos sobre <strong style="color:#242436">${business}</strong>. Recibimos tu consulta y vamos a revisarla para proponerte un próximo paso concreto.</p><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f7f7fc;border:1px solid #ececf3;border-radius:14px"><tr><td style="padding:18px 20px"><p style="margin:0 0 7px;font-size:11px;letter-spacing:1.2px;color:#79798c;text-transform:uppercase">Tu consulta</p><p style="margin:0;font-size:16px;font-weight:700;color:#242436">${service}</p></td></tr></table></td></tr><tr><td style="padding:28px 32px 36px"><h2 style="font-size:20px;letter-spacing:-.4px;margin:0 0 12px">¿Lo vemos en una charla?</h2><p style="font-size:15px;line-height:1.65;color:#56566d;margin:0 0 24px">Elegí un horario con Santiago. Vemos cómo trabajás hoy, qué querés mejorar y cuál puede ser una primera implementación útil para tu negocio.</p><table role="presentation" cellspacing="0" cellpadding="0"><tr><td bgcolor="#4F46F5" style="border-radius:10px"><a href="${CALENDLY_URL}" style="display:inline-block;padding:17px 25px;color:#ffffff;font-size:15px;font-weight:700;text-decoration:none;border:1px solid #4F46F5;border-radius:10px">Elegir un horario&nbsp; →</a></td></tr></table><p style="font-size:13px;line-height:1.6;color:#78788c;margin:22px 0 28px">Si preferís, respondé este correo y contanos un poco más.</p><p style="margin:0;font-size:15px;line-height:1.7;color:#242436"><strong>Santiago</strong><br><span style="color:#777789">IMAN</span></p></td></tr>`)
  };
}

export function ownerEmail(lead) {
  const fields = [
    ['Nombre', lead.nombre], ['Negocio', lead.negocio], ['Servicio', lead.servicio],
    ['Email', lead.email], ['WhatsApp', lead.whatsapp || 'No indicado'],
    ['Consulta', lead.comentario || 'Sin comentario adicional'],
    ['Página', lead.source || 'No indicada'],
    ...Object.entries(lead.utm).map(([key, value]) => [key, value])
  ];
  return {
    subject: `Nueva consulta IMAN · ${lead.negocio}`,
    text: `Nueva consulta desde iman.ar\n\n${fields.map(([key,value]) => `${key}: ${value}`).join('\n')}\n\nAutorizó recibir una respuesta a su consulta. Respondé este correo para contactar al cliente.`,
    html: frame('Nueva consulta de un negocio desde iman.ar.', `<tr><td style="padding:32px"><h1 style="font-size:26px;margin:0 0 24px">Nueva consulta</h1><table role="presentation" width="100%" cellspacing="0" cellpadding="0">${fields.map(([key, value]) => `<tr><td style="padding:12px 0;border-bottom:1px solid #ececf3;vertical-align:top;width:100px;font-size:12px;color:#777789">${escapeHTML(key)}</td><td style="padding:12px 0 12px 12px;border-bottom:1px solid #ececf3;font-size:14px;line-height:1.5;overflow-wrap:anywhere;white-space:pre-wrap">${escapeHTML(value)}</td></tr>`).join('')}</table><p style="font-size:12px;color:#777789;line-height:1.6;margin:24px 0 0">Autorizó recibir una respuesta a su consulta. Respondé este correo para contactar al cliente.</p></td></tr>`)
  };
}
