// Carrusel 01/10/2026 (18 h) — ¿Sellos o puntos? Cómo elegir el sistema del club.
// Uso: node build.mjs → 01–07.html/png. Chrome headless por DevTools (sin dependencias).
import {spawn} from 'node:child_process';
import {setTimeout as sleep} from 'node:timers/promises';
import {readFileSync,writeFileSync,rmSync} from 'node:fs';
import path from 'node:path';
const dir=path.dirname(new URL(import.meta.url).pathname),assets=path.resolve(dir,'../../experience/assets');
const font=n=>readFileSync(path.join(assets,n)).toString('base64');
const D=font('playfair-display-sc.ttf'),B=font('libre-baskerville-regular.ttf');
const slides=[
 {tag:'FIDELIZACIÓN · CLUB DE CLIENTES',title:'¿Sellos<br>o puntos?',body:`<p class="lead">Cómo elegir el sistema de tu club<br>según cómo te compran.</p><pre class="ascii">sellos   ● ● ● ● ● ○ ○ ○   cuentan visitas
puntos   1.240 pts         cuentan gasto</pre>`,cover:true},
 {tag:'01 · SELLOS',title:'Los sellos<br>cuentan visitas.',body:`<ul class="list"><li><b>Ticket parecido</b><span>cada compra vale más o menos lo mismo</span></li><li><b>Un solo premio</b><span>un producto o servicio fijo al completar</span></li><li><b>Se explica en una frase</b><span>«juntás ocho y el noveno va de regalo»</span></li></ul>`},
 {tag:'02 · PUNTOS',title:'Los puntos<br>cuentan gasto.',body:`<ul class="list"><li><b>Ticket variable</b><span>una compra chica y una grande no pesan igual</span></li><li><b>Premia al que más compra</b><span>el acumulado sigue al importe, no a la visita</span></li><li><b>Pide tabla de canje</b><span>cuánto vale un punto y qué se puede canjear</span></li></ul>`},
 {tag:'03 · LA PRUEBA',title:'Tres preguntas<br>para decidir.',body:`<ul class="list q"><li><span>¿Tus tickets se parecen o varían mucho?</span></li><li><span>¿Buscás más visitas o más gasto por visita?</span></li><li><span>¿Lo podés explicar en la caja en diez segundos?</span></li></ul><p class="fine">Parecidos, visitas y diez segundos: sellos.<br>Variables y gasto: puntos.</p>`},
 {tag:'DOS EJEMPLOS',title:'El mismo club,<br>dos mecánicas.',body:`<div class="card"><div class="clabel">CAFETERÍA · TICKET PAREJO</div><div class="row"><span>SISTEMA</span><b>Sellos</b></div><div class="row"><span>REGLA</span><b>8 cafés, el 9.º gratis</b></div></div><div class="card"><div class="clabel">PET SHOP · TICKET VARIABLE</div><div class="row"><span>SISTEMA</span><b>Puntos</b></div><div class="row"><span>REGLA</span><b>1 punto cada $ 1.000</b></div><div class="row"><span>CANJE</span><b>desde 50 puntos</b></div></div>`},
 {tag:'LO QUE NO RESUELVE',title:'La mecánica<br>no reemplaza<br>al premio.',body:`<p class="lead">Si el premio no interesa o queda<br>demasiado lejos, ni los sellos<br>ni los puntos lo arreglan.</p><pre class="ascii flow">premio alcanzable  +  regla simple</pre><p class="fine">Si más adelante cambiás de sistema, avisá<br>qué pasa con lo que ya acumularon.</p>`},
 {tag:'LA DECISIÓN DE TU NEGOCIO',title:'En tu negocio,<br>¿sellos o puntos?',body:`<div class="choices"><span>Sellos</span><span>Puntos</span><span>Todavía no sé</span></div><p class="fine">Contá tu rubro y cuánto varía<br>tu ticket de una compra a otra.</p>`}
];
const N=slides.length;
function html(s,i){return `<!doctype html><meta charset="utf-8"><style>
@font-face{font-family:P;src:url(data:font/ttf;base64,${D})}@font-face{font-family:B;src:url(data:font/ttf;base64,${B})}*{box-sizing:border-box;font-variant-ligatures:none}body{margin:0;width:1080px;height:1350px;background:#11141b;color:#eef0f4;font-family:B}main{position:relative;width:1080px;height:1350px;padding:65px 76px;overflow:hidden}header{display:flex;justify-content:space-between;border-bottom:1px solid #94a4bc66;padding-bottom:31px;color:#aab7cb;font:20px monospace;letter-spacing:2px}.brand{color:#eef0f4;font:30px P}.tag{margin:46px 0 37px;color:#94a4bc;font:22px monospace;letter-spacing:2px}.tag i{color:#f4c430;font-style:normal}h1{font:normal 77px/1.15 P;margin:0 0 40px;letter-spacing:-3px}.cover h1{font-size:84px;margin-top:40px}.lead{font:32px/1.6 B;color:#c8d0dc;margin:36px 0}.fine{font:24px/1.6 B;color:#a3afc2;margin:30px 0}.ascii{font:24px/1.35 monospace;color:#94a4bc;margin:40px 0}.flow{font-size:27px;color:#eef0f4;border-top:1px solid #526075;border-bottom:1px solid #526075;padding:30px 0;text-align:center}.list{list-style:none;padding:0;margin:20px 0}.list li{padding:22px 0;border-bottom:1px solid #536075;display:flex;flex-direction:column;gap:10px}.list b{font:normal 46px P}.list span{font:26px/1.5 B;color:#b9c3d4}.q{counter-reset:q}.q li{flex-direction:row;align-items:baseline;gap:28px;padding:30px 0}.q li:before{counter-increment:q;content:'0' counter(q);font:22px monospace;color:#f4c430}.q span{font:34px/1.45 B;color:#eef0f4}.card{border:1px solid #8190a8;background:#19212d;padding:26px 34px;margin:0 0 26px}.card+.card{background:#151b25;border-color:#536075}.clabel{color:#aab7cb;font:20px monospace;letter-spacing:2px;margin-bottom:8px}.row{display:flex;justify-content:space-between;align-items:baseline;padding:13px 0;border-bottom:1px solid #53607555}.row:last-child{border:0}.row span{font:20px monospace;color:#94a4bc;letter-spacing:2px}.row b{font:normal 34px B}.chat{color:#c8d0dc;font-size:30px;line-height:1.75;border-left:1px solid #536075;padding-left:30px}.msg{font:27px/1.5 monospace;color:#eef0f4;margin:10px 0 0}.choices{display:flex;flex-wrap:wrap;gap:18px;margin:50px 0}.choices span{border:1px solid #7d8ca4;padding:25px 28px;font:32px B}.footer{position:absolute;bottom:62px;left:76px;right:76px;border-top:1px solid #94a4bc66;padding-top:26px;display:flex;justify-content:space-between;color:#94a4bc;font:18px monospace;letter-spacing:1px}.footer b{color:#f4c430;font-weight:normal}
</style><main class="${s.cover?'cover':''}"><header><span class="brand">IMÁN</span><span>IDEAS PARA TU NEGOCIO</span></header><div class="tag">${s.tag.replace(/^(\d\d)/,'<i>$1</i>')}</div><h1>${s.title}</h1>${s.body}<div class="footer"><span>${i===4?'EJEMPLOS HIPOTÉTICOS · NO SON CASOS REALES':'ESTUDIO.IMAN'}</span><span><b>0${i+1}</b> / 0${N}</span></div></main>`}
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',PORT=9338,UD=`/tmp/iman_carrusel_${Date.now()}`;
const chrome=spawn(CHROME,['--headless=new','--disable-gpu','--hide-scrollbars',`--remote-debugging-port=${PORT}`,'--remote-allow-origins=*',`--user-data-dir=${UD}`,'about:blank'],{stdio:'ignore'});
try{
let ver;for(let i=0;i<75&&!ver;i++){try{ver=await (await fetch(`http://127.0.0.1:${PORT}/json/version`)).json()}catch{await sleep(200)}}
const ws=new WebSocket(ver.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));
let id=0;const pending=new Map();ws.addEventListener('message',ev=>{const m=JSON.parse(ev.data);if(m.id&&pending.has(m.id)){pending.get(m.id)(m);pending.delete(m.id)}});
const send=(method,params={},sessionId)=>new Promise((res,rej)=>{const i=++id;pending.set(i,m=>m.error?rej(new Error(method+JSON.stringify(m.error))):res(m.result));ws.send(JSON.stringify({id:i,method,params,sessionId}))});
const {targetId}=await send('Target.createTarget',{url:'about:blank'});const {sessionId}=await send('Target.attachToTarget',{targetId,flatten:true});
await send('Emulation.setDeviceMetricsOverride',{width:1080,height:1350,deviceScaleFactor:1,mobile:false},sessionId);
for(let i=0;i<N;i++){const file=path.join(dir,`0${i+1}.html`);writeFileSync(file,html(slides[i],i));
 await send('Page.navigate',{url:'file://'+file},sessionId);await sleep(900);
 const {result}=await send('Runtime.evaluate',{expression:`document.fonts.ready.then(()=>{const f=document.querySelector('.footer'),p=f.previousElementSibling;return p.getBoundingClientRect().bottom<f.getBoundingClientRect().top-12})`,awaitPromise:true,returnByValue:true},sessionId);
 if(!result.value)throw Error(`Lámina ${i+1} pisa el pie`);
 const {data}=await send('Page.captureScreenshot',{format:'png'},sessionId);writeFileSync(path.join(dir,`0${i+1}.png`),Buffer.from(data,'base64'));}
ws.close();console.log(`${N} láminas renderizadas; margen del pie verificado.`);
}finally{chrome.kill();try{rmSync(UD,{recursive:true,force:true})}catch{}}
